### ISSUE TITLE
Cannot find Application class

### ISSUE THREAD

**Issue by michaelpolakatwork** [qooxdoo/qooxdoo#10124]
I have an existing qooxdoo application built with version 4.1 that I am migrating the 6.0.  I used the create command to create a default setup with folders and then put my existing source into the source folder.  I then modified the config.json and Manifest.json to match the code I was migrating. I then tried to compile the code and got this message:

Cannot find class file latte.Application
Error: TypeError: Cannot read property 'getRootDir' of nullcation sb3
    at wrapper._writeIndexHtml (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:53054:54)
    at wrapper._writeApplication (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:52978:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:27354:29)
    at doThenable (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:31349:23)
    at tryConvertToPromise (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:31314:26)
    at PromiseArray._iterate (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30080:36)
    at PromiseArray.init [as _init] (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30068:20)
    at new PromiseArray (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:30013:20)
    at Function.Promise.all (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:29268:22)
    at Function.__P_64_8 (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:26101:68)
    at Function.all (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:25686:27)
    at wrapper._loadConfigAndStartMaking (d:\home\Latte\sb3\node_modules\@qooxdoo\compiler\lib\compiler\index.js:51357:26)

In my source\class\latte folder I do have an Application.js file that has qx.Class.define("latte.Application".  So it seems to be there.

My manifest is here:
{
 "$schema": "https://qooxdoo.org/schema/Manifest-1-0-0.json",
  "info" :
  {
    "name" : "sb3",
    "summary" : "",
    "description" : "",
    "homepage" : "",
    "license" : "MIT license",
    "authors" : [
  {
    "name": "",
    "email": ""
  }
],

    "version" : "1.0.0"
  },

  "provides" :
  {
    "namespace"   : "latte",
    "encoding"    : "utf-8",
    "class"       : "source/class",
    "resource"    : "source/resource",
    "translation" : "source/translation"
  },

  "requires": {
    "@qooxdoo/framework": "^6.0.0",
    "@qooxdoo/compiler" : "^1.0.0",
    "qooxdoo/qxl.dialog": "^3.0.4"
  }
}

and there is my compile.json

{
  "$schema": "https://qooxdoo.org/schema/compile-1-0-0.json",
  "targets": [
    {
      "type": "source",
      "outputPath": "compiled/source",
      "bundle": {
        "include": "qx.*"
      }
    },
    {
      "type": "build",
      "outputPath": "compiled/build",
	  "deployPath": "www"
    }
  ],
  "defaultTarget": "source",
  "locales": ["en"],
  "environment": {
      "qx.icontheme": "Tango"
  },
  "applications": [
    {
      "class": "latte.Application",
      "theme": "latte.theme.Theme",
      "name": "sb3",
      "bootPath": "source/boot",
      "include": [
        "latte.Load"
      ]	  
    }
  ]
}

Any idea what I am missing?

**Comment by michaelpolakatwork** [comment]
Looks like the problem may be related to a custom library I am using.  It worked fine in the beta version but now it looks like it wants to find an Application in the library.  I'll update again if I find out why.

**Comment by hkollmann** [comment]
Do you find the problem?

**Comment by hkollmann** [comment]
No answer ...
