### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10189]
```sh
npm install --save-dev @qooxdoo/compiler
added 1025 packages, and audited 1026 packages in 1m

4 vulnerabilities (3 low, 1 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

then
```sh
$ npx qx

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:790:3)
    at Object.getInstalledBinaries (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (./node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at ./node_modules/@qooxdoo/compiler/lib/compiler/index.js:44898:14
    at Object.<anonymous> (./node_modules/@qooxdoo/compiler/lib/compiler/index.js:44995:3)   
```

My environment is Ubuntu 20.04.2 LTS with:
```sh
$ node --version
v10.19.0
$ npm --version
7.9.0
$ uname -r
5.8.0-49-generic
```

**Comment by adrelino** [comment]
I had the same issue again just now when deploying on a server.

But there I additionally needed to run
```
node node_modules/@qooxdoo/compiler/node_modules/node-sass/scripts/install.js
```
(see https://stackoverflow.com/a/53669612)

before
```
npm rebuild node-sass
```
so that the folder `node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor` gets created.

**Comment by hkollmann** [comment]
fixed with https://github.com/qooxdoo/qooxdoo-compiler/pull/823
