### ISSUE TITLE
unable to start: "no such file or directory" for node-sass/vendor

### ISSUE THREAD

**Issue by dedalus2000** [qooxdoo/qooxdoo#10180]
I'm trying to install Qooxdoo:
npm install -g @qooxdoo/framework

but I immediately have the following error when I try to execute "qx" (or "npx qx": I tried both global and local installations):

$  qx
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:1021:3)
    at Object.getInstalledBinaries (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /opt/node/lib/node_modules/@qooxdoo/compiler/lib/compiler/index.js:44898:14
    at Object.<anonymous> (/opt/node/lib/node_modules/@qooxdoo/compiler/lib/compiler/index.js:44995:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/opt/node/lib/node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'
}

Somewhere I read to execute "npm rebuild node-sass" but It does not work for me.

OS:    Ubuntu 20.04.2 LTS "focal" (kernel 5.4.0)
npm: 7.6.3
node: 14.16.0

**Comment by dedalus2000** [comment]
Found the solution:
npm rebuild node-sass --force

I also forgot npm update , but alone it didn't solve the problem

Now it works fine:
$ qx

qooxdoo command line interface
==============================
Versions: @qooxdoo/compiler    v1.0.0

....
....
