### ISSUE TITLE
Regression: tabbing to radio button group causes crash

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo#10227]
Since #10200 (83c540a71a7a280c009ddbdc5405950666f9abfc), tabbing to a radio button group causes a crash. Using this Application.js in a newly-created desktop app with compile.json pointing to a checkout of qooxdoo (master or ) as one of its libraries, the program crashes when you tab from the Username field to the radio button group.

```
qx.Class.define("xxx.Application",
{
  extend : qx.application.Standalone,

  members :
  {
    main : function()
    {
      this.base(arguments);

      if (qx.core.Environment.get("qx.debug"))
      {
        qx.log.appender.Native;
        qx.log.appender.Console;
      }

      var doc = this.getRoot();
      var container = new qx.ui.container.Composite(new qx.ui.layout.VBox());
      doc.add(container, { edge : 10 });

      var form = new qx.ui.form.Form();

      var username = new qx.ui.form.TextField();
      form.add(username, "Username");
      
      let radioGroup = new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(4));
      let radioButton = new qx.ui.form.RadioButton("Male");
      radioGroup.add(radioButton);
      radioButton = new qx.ui.form.RadioButton("Female");
      radioGroup.add(radioButton);
      form.add(radioGroup, "Radio Group");
      

      var renderer = new qx.ui.form.renderer.Single(form);

      container.add(new qx.ui.basic.Label("Here's my form"));
      container.add(renderer);
    }
  }
});
```

The crash message shows:

```
Native.js:59 003867 qx.ui.core.queue.Appearance: Error in the 'Appearance' queue:TypeError: this.warn is not a function TypeError: this.warn is not a function
file:///tmp/xxx/compiled/source/xxx/package-5.js:7868:18,Array.forEach (<anonymous>),file:///tmp/xxx/compiled/source/xxx/package-5.js:7864:25,file:///tmp/xxx/compiled/source/xxx/package-5.js:11127:19,file:///tmp/xxx/compiled/source/xxx/package-5.js:45908:58,file:///tmp/xxx/compiled/source/xxx/package-1.js:14313:25,eval at __installFunctionFromCode__P_8_13 (file:///tmp/xxx/compiled/source/xxx/package-1.js:6298:38,eval at __installFunctionFromCode__P_8_13 (file:///tmp/xxx/compiled/source/xxx/package-1.js:6298:38,file:///tmp/xxx/compiled/source/xxx/package-5.js:11486:86,file:///tmp/xxx/compiled/source/xxx/package-5.js:33278:17,file:///tmp/xxx/compiled/source/xxx/package-3.js:1041:47,file:///tmp/xxx/compiled/source/xxx/package-3.js:1108:9,file:///tmp/xxx/compiled/source/xxx/package-3.js:1011:14,file:///tmp/xxx/compiled/source/xxx/package-1.js:18693:39,file:///tmp/xxx/compiled/source/xxx/package-1.js:29114:22,file:///tmp/xxx/compiled/source/xxx/package-1.js:18692:28
```

The actual crash is in `qx.html.Element`, in method `removeClass`.

Attn: @johnspackman

**Comment by derrell** [comment]
I think maybe this a fix:

```
modified   source/class/qx/html/Element.js
@@ -1854,7 +1854,7 @@ qx.Class.define("qx.html.Element",
     addClass : function(name) {
       var classes = this.__breakClasses();
       var primaryClass = (this.getCssClass()||"").toLowerCase();
-      name.split(" ").forEach(function(name) {
+      name.split(" ").forEach((name) => {
         var nameLower = name.toLowerCase();
         if (nameLower == primaryClass) {
           this.warn("Adding CSS Class " + name + " when it is the primary CSS class (consider using .setCssClass instead)");
@@ -1877,7 +1877,7 @@ qx.Class.define("qx.html.Element",
     removeClass : function(name) {
       var classes = this.__breakClasses();
       var primaryClass = (this.getCssClass()||"").toLowerCase();
-      name.split(" ").forEach(function(name) {
+      name.split(" ").forEach((name) => {
         var nameLower = name.toLowerCase();
         if (nameLower == primaryClass) {
           this.warn("Removing CSS Class " + name + " when it is the primary CSS class (consider using .setCssClass instead)");
@@ -1911,7 +1911,7 @@ qx.Class.define("qx.html.Element",
     _applyCssClass: function(value, oldValue) {
       var classes = this.__breakClasses();
       if (oldValue) {
-        value.split(" ").forEach(function(name) {
+        oldValue.split(" ").forEach(function(name) {
           delete classes[name.toLowerCase()];
         });
       }
```

The first two changes ensure that `this` has the correct value. The final change looks like it was a typo that caused a crash once it got past the problem fixed by the first two changes.

I'm working in the blind here, though, not really understanding what these changes were trying to accomplish...
