### ISSUE TITLE
Wrong colors in IndigoDark for some widgets and states

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10517]
Looking through Widget Browser I've noticed there are some widget has bad/not suitable colors for theme. Firstly it is a tooltip. There is black color of text and white background. Need to be vice versa. Secondly it is a hovered MenuBar button: both text and background colors during hover are the same (white).

**Comment by goldim** [comment]
![image](https://user-images.githubusercontent.com/22189134/211048505-72a22047-1b57-4f00-8f9a-b38a7d9a14af.png)

**Comment by sknick** [comment]
I am unable to event get that tab to load. I get the following stack trace:

```
Widget.js:3297 Uncaught Error: Exception while creating child control 'icon' of widget qx.ui.toolbar.Button[845-0]: Cannot find font in virtual image source: '@MaterialIcons/arrow_back/16'
    at wrapper.__getFont__P_35_20 (Image.js:891:15)
    at wrapper.__setManagedImage__P_35_15 (Image.js:762:27)
    at wrapper._styleSource (Image.js:495:14)
    at wrapper._applySource (Image.js:323:12)
    at wrapper.set (eval at __installFunctionFromCode__P_56_13 (Property.js:1001:36), <anonymous>:3:1252)
    at wrapper.eval [as $$setSourceImpl] (eval at __installFunctionFromCode__P_56_13 (Property.js:1001:36), <anonymous>:6:258)
    at wrapper.eval [as setSource] (eval at __installFunctionFromCode__P_56_13 (Property.js:1001:36), <anonymous>:3:22)
    at wrapper.construct (Image.js:65:12)
    at new wrapper (Class.js:1807:39)
    at wrapper._createChildControlImpl (Atom.js:208:21)
    at wrapper._createChildControl (Widget.js:3282:30)
    at wrapper.getChildControl (Widget.js:3186:19)
    at wrapper._showChildControl (Widget.js:3196:26)
    at wrapper._handleIcon (Atom.js:247:14)
    at wrapper._applyIcon (Atom.js:276:12)
    at wrapper.set (eval at __installFunctionFromCode__P_56_13 (Property.js:1001:36), <anonymous>:3:1189)
```

**Comment by goldim** [comment]
Did you get last changes from master? There was PR related to fix some things about IndigoDark theme.

**Comment by sknick** [comment]
Perhaps this has something to do with bootstrapping the compiler and installing via `npm install --save <local qooxdoo>`? I really have no idea.

**Comment by sknick** [comment]
I guess I should elaborate and say that this issue isn't specific to the new theme... I've never been able to get that tab to load in the widget browser, even prior to the new theme.

**Comment by goldim** [comment]
@sknick I used some old widget browser from my fork project (theme). Just added IndigoDark theme there and checked how it works. I will try to add Widget Browser as dependency into new theme project. Probably instead of building widget browser as separate project install it as package from qooxdoo package system?

**Comment by goldim** [comment]
@sknick Yes, there is an error which you've described in toolbar/menu. 
I used qooxdoo compiler/framework with current changes.

1. ..\qooxdoo\bootstrap\qx create test --type package --out . -I  
2. ..\qooxdoo\bootstrap\qx package install qooxdoo/qxl.widgetbrowser
3. ..\qooxdoo\bootstrap\qx package install qooxdoo/qxl.versionlabel 
4. ..\qooxdoo\bootstrap\qx package install qooxdoo/qxl.formdemo     
5. npx qx serve -S

**Comment by sknick** [comment]
So I followed your steps above but I'm still getting the same stack trace.

**Comment by sknick** [comment]
I'm seeing this when I compile Qooxdoo after installing the packages you specified:

```
Assets required for webfont MaterialIconsOutlined are not available in application widgetbrowser, consider using @asset to include qx/iconfont/MaterialIcons/materialiconsoutlined-v101.eot,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.woff2,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.woff,qx/iconfont/MaterialIcons/materialiconsoutlined-v101.otf
```

**Comment by goldim** [comment]
I've created an issue about Material Icons in qxl.widgetbrowser but there is compiled version which runs on github pages.
