### ISSUE TITLE
Compiler crash with sr_Latn locale

### ISSUE THREAD

**Issue by bgrange-inheart** [qooxdoo/qooxdoo#10522]
**Describe the bug**
When adding the "sr_Latn" string to the locales array, the compiler crash:
```
Error: TypeError: Cannot read properties of undefined (reading 'length')
    at /tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:55697:47
    at find (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:55501:26)
    at /tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:55696:15
    at find (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:55501:26)
    at /tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:55695:13
    at async /tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:47965:22
From previous event:
    at Function.__P_143_8 (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:20570:69)
    at Function.all (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:20146:27)
    at wrapper._writeLocales (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:47969:26)
    at wrapper._writeTranslations (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:47887:20)
    at wrapper.generateApplication (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:47787:98)
    at async wrapper.make (/tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:49898:11)
    at async /tmp/testlocale/node_modules/@qooxdoo/framework/lib/compiler/index.js:46429:20
```

**To Reproduce**
You can use this project [crash_locale.zip](https://github.com/qooxdoo/qooxdoo/files/10373577/crash_locale.zip). Created by following the tutorial [The First Application](https://qooxdoo.org/documentation/v7.4/#/README?id=the-first-application) and by adding sr_Latn to the locales array in compile.json (but any project will crash)

1. Unzip the crash_locale.zip
2. npm i && npx qx compile

**Expected behavior**
No compiler crash

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser NA
 - Version  NA

**Comment by goldim** [comment]
@bgrange-inheart The name of language/locale is two letter word e.g. en/ru/fr/ro and so on. You may try "sr" but for basic widgets there are no translation. By the way you may add your language support in qooxdoo framework via Pull Request. For it you have to create <your language>.po file by [this](https://github.com/qooxdoo/qooxdoo/blob/master/source/translation) path. Also there are other language files. You can take for base one of them.

**Comment by derrell** [comment]
Yes to what @goldim said... but still, the compiler shouldn't crash if given bad input. It should complain in a  controlled way, instead.

**Comment by goldim** [comment]
I started investigation, full name of locale has to work, but sr_Latn is converted to sr_LATN (uppercase) and there is not file with it (but file sr_Latn.xml exists). Obviously it is a bug and there is also unhandled promise.

**Comment by goldim** [comment]
```
_transformLocales(value) {
      if (!value) {
        return value;
      }
      return value.map(localeId => {
        localeId = localeId.toLowerCase();
        var pos = localeId.indexOf("_");
        if (pos > -1) {
          localeId =
            localeId.substring(0, pos) + localeId.substring(pos).toUpperCase();
        }
        return localeId;
      });
    },
```
this code causes converting to uppercase.

**Comment by hkollmann** [comment]
Seems that the case converting is wrong. Locale files are written in cammel case notation. see

**Comment by goldim** [comment]
The error happens bc `sr_Latn` causes to load "root.xml" locale file which doesn't have abbreviations for months. Btw I've found another error by myself accidentally investigating this problem. The error was found on Linux (Debian) and related with case sensitivity. Complex locales which have `_` after first two letters are transformed into lower case and `readFile` (of NodeJS module `fs`) can not find the file. In Windows `readFile` is case insensitive and read files in any case.
