### ISSUE TITLE
Defining a non existing `localModules` breakes the compiler in a strange way

### ISSUE THREAD

**Issue by ChristianMayer** [qooxdoo/qooxdoo#10554]
**Describe the bug**
I had in my `compile.json` an entry to a ressource that didn't exist (anymore) like
```
...
  "applications": [
    {
      "localModules": {
        "grafModel": "./source/local_modules/grafModel/test.js"
      }
```
This made the compiler fail with
```
Error: TypeError: Cannot read properties of null (reading 'mtime')
    at wrapper.writeToDisk (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:55192:58)
    at async wrapper.writeToDisk (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:61019:13)
    at async wrapper._writeApplication (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:48110:11)
    at async wrapper._writeApplication (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:54144:16)
    at async wrapper.generateApplication (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:47876:9)
    at async wrapper.make (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:49908:11)
    at async /home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:46439:20
From previous event:
    at Function.__P_143_8 (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:20570:69)
    at Function.all (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:20146:27)
    at wrapper._loadConfigAndStartMaking (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:46366:26)
    at async wrapper.process (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:46326:9)
    at async wrapper.processCommand (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:35261:21)
    at async wrapper.main (/home/cm/devel/grafweb/node_modules/@qooxdoo/framework/lib/compiler/index.js:34736:11)
```

**To Reproduce**
see above

**Expected behavior**
A clear message from the compiler that I configured a non existing module and not a stack trace in an area that didn't help in any way to find the root of the problem

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [Linux
 - "Browser": node 18

**Comment by derrell** [comment]
I can't test this to confirm, but I believe this is the required fix:

```
modified   source/class/qx/tool/compiler/targets/meta/Browserify.js
@@ -102,6 +102,16 @@ qx.Class.define("qx.tool.compiler.targets.meta.Browserify", {
             localModules[requireName]
           );
 
+          if (! stat)
+          {
+            // There's a local module that we're told to include, but it doens't exist
+            let message = [];
+            message.push(`ERROR: could not locate require()d module: "${requireName}"`);
+            message.push("  required from:  <compile.json:application.localModules'>");
+            qx.tool.compiler.Console.error(message.join("\n"));
+            continue;
+          }
+
           modulesInfo.localModules[requireName] = stat.mtime.getTime();
           doIt ||=
             modulesInfo.localModules[requireName] >
```

**Comment by hkollmann** [comment]
moved to esbuild in v8
