### ISSUE TITLE
Previous configuration of webfonts doesn't work

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10564]
**Describe the bug**
Old configuration of webfonts seems like doesn't work and not supported.

**To Reproduce**
Add following content to relevant files.
**Manifest.json**:
```
"webfonts": [
      {
        "name": "FontAwesome",
        "defaultSize": 16,
        "mapping": "resource/bernstein/fonts/fontawesome.map",
        "resources": [
          "resource/bernstein/fonts/fa-solid-900.ttf"
        ]
      }
    ],
```

**theme.Font.js**:
```
"fontawesome": {
      size: 14,
      lineHeight: 1,
      comparisonString: "\uf1e3\uf1f7\uf11b\uf19d",
      family: ["FontAwesome"],
      sources: [
        {
          family: "FontAwesome",
          source: ["resource/bernstein/fonts/fa-solid-900.ttf"]
        }
      ]
    },
```

**Expected behavior**
Previous configuration of webfonts should work and no errors to be resulted.

**Error trace**
```
Font.js:213 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _loop (Font.js:213:18)
    at wrapper.__initialiseFonts__P_67_0 (Font.js:205:36)
    at wrapper._applyTheme (Font.js:335:29)
    at wrapper.set (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:3:1075)
    at wrapper.eval [as $$setThemeImpl] (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:6:258)
    at wrapper.eval [as setTheme] (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:3:21)
    at wrapper.eval (eval at __attachPropertyMethods__P_41_7 (Property.js:717:26), <anonymous>:3:84)
    at wrapper._applyTheme (Meta.js:80:7)
    at wrapper.set (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:3:1118)
    at wrapper.eval [as $$setThemeImpl] (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:4:258)
    at wrapper.eval [as setTheme] (eval at __installFunctionFromCode__P_41_13 (Property.js:1001:36), <anonymous>:3:21)
    at wrapper.eval (eval at __attachPropertyMethods__P_41_7 (Property.js:717:26), <anonymous>:3:84)
    at wrapper.initialize (Meta.js:196:10)
    at wrapper.main (AbstractGui.js:69:43)
    at wrapper.main (Application.js:29:7)
```

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Chrome
 - Version 100+

**Comment by johnspackman** [comment]
see https://github.com/qooxdoo/qooxdoo/pull/10566
