### ISSUE TITLE
qx config doesn't work

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10571]
**Describe the bug**
Get the error:
```
goldim@goldim:~/WebstormProjects/ugpa.completer$ qx config list
Error: TypeError: Cannot read properties of null (reading 'getTargetType')
    at wrapper.__P_3_8 (/home/goldim/WebstormProjects/ugpa.completer/node_modules/@qooxdoo/framework/lib/compiler/index.js:35512:56)
    at async wrapper.run (/home/goldim/WebstormProjects/ugpa.completer/node_modules/@qooxdoo/framework/lib/compiler/index.js:35294:9)
    at async wrapper.main (/home/goldim/WebstormProjects/ugpa.completer/node_modules/@qooxdoo/framework/lib/compiler/index.js:34734:11)
```

**To Reproduce**
1. Create new project
2. Run `qx config list` or `qx config set`

**Expected behavior**
No error

**Env Info (please complete the following information):**
 - OS: Debian
 - qooxdoo framework 7.5.1

**Comment by goldim** [comment]
For some reasons setCommand is not called for any of "set", "get", "list" subcommand of `qx config` and there is no command during `_applyCommand`. In the command Config there is yargs.command is used but nowhere else. Maybe to create separate classes for Config like for Package done?
