### ISSUE TITLE
Errors during test-issues

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10584]
```
# Dynamic commands
The commmand testlib; message=hello, type=4
Error: TypeError: Cannot read properties of null (reading 'getTargetType')
    at wrapper.__P_3_10 (C:\qx\qooxdoo\compiled\node\build\compiler\index.js:35629:56)
    at async wrapper.run (C:\qx\qooxdoo\compiled\node\build\compiler\index.js:35409:9)
    at async wrapper.main (C:\qx\qooxdoo\compiled\node\build\compiler\index.js:34850:11)
ok 12 should be truthy
# Issue440
##qx.tool.cli.compile.makeBegins:[]
SyntaxError: C:\qx\qooxdoo\test\tool\integrationtest\test-issues\issue440\source\class\issue440\Application.js: Missing semicolon. (41:4)

  39 |       this.base(arguments);
  40 |
> 41 | This is an error
     |     ^
  42 |
  43 |       // Enable logging in debug variant
  44 |       if (qx.core.Environment.get("qx.debug"))
issue440.Application: [41,4] error: FATAL Syntax error: C:\qx\qooxdoo\test\tool\integrationtest\test-issues\issue440\source\class\issue440\Application.js: Missing semicolon. (41:4)

  39 |       this.base(arguments);
  40 |
> 41 | This is an error
     |     ^
  42 |
  43 |       // Enable logging in debug variant
  44 |       if (qx.core.Environment.get("qx.debug"))
```

**Comment by goldim** [comment]
These errors are on purpose in test.
