### ISSUE TITLE
qx package list outside of a project folder

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#10588]
**Describe the bug**
Executing `qx package list` outside of a qooxdoo project leads to an error:
```
Error: Error: Cannot load config file: Manifest.json does not exist. Are you in the library root?
    at wrapper.load (/usr/local/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js:36974:19)
    at async Object.getAppQxVersion (/usr/local/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js:36551:29)
    at async wrapper.process (/usr/local/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js:43567:25)
    at async wrapper.processCommand (/usr/local/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js:35261:21)
    at async wrapper.main (/usr/local/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js:34736:11)
```
**Expected behavior**
The commands such as `qx package list` have to work everywhere.

**Comment by cboulanger** [comment]
The problem is that `qx package list` needs to know which qooxdoo version a qooxdoo project has been compiled with in order to determine if the packages are compatible or not. Thus, running it outside of a project is meaningless in a way, because what's ther purpose of listing packages that you cannot use because they are incompatible. But of course the error message should be different.

**Comment by goldim** [comment]
@cboulanger oh thank you. Unless the error message I would close the issue. Then try to fix it.
