### ISSUE TITLE
Bootstrap failing on linux

### ISSUE THREAD

**Issue by p9malino26** [qooxdoo/qooxdoo#10618]
I try to compile the compiler on Linux, but fail.

# Steps to reproduce:
`$ git clone https://github.com/qooxdoo/qooxdoo.git`
`$ cd qooxdoo`
`$ npm ci`
`$ ./bootstrap-compiler`

Unfortunately, this is what I get after running the last command:
[out.txt](https://github.com/qooxdoo/qooxdoo/files/12328033/out.txt)

Based on what I have found out, the `rem` function in CSS requires two arguments but only one was given (https://developer.mozilla.org/en-US/docs/Web/CSS/rem). Adding the value '1' as the second argument for every call of `rem` across the whole source of Qx makes the compiler compile. I don't understand how this code is supposed to work if there are many instances in the Qx source where `rem` is passed one argument instead of two?

# System info:
- OS: Arch Linux 64-bit
- NodeJs version: 16.20.2 (downloaded from nodejs.org)

**Comment by WillsterJohnsonAtZenesis** [comment]
Reproduced this on OSX Monterey.

<details>
  <summary>bootstrap output</summary>
  <pre><code>
./bootstrap-compiler
Deleting previous bootstrap compiler
Creating temporary compiler with known-good one
***
*** Known Good Compiler Version: 7.6.1
***
run /Users/will/dev/qooxdoo/known-good/node_modules/.bin/qx compile --target=build
Making applications...
Error: Error: 2 arguments required, but only 1 was passed.
   ╷
62 │   @include border-radius(rem(4));
   │                          ^^^^^^
   ╵
  ../source/resource/qx/mobile/scss/common/_scroller.scss 62:26  @import
  ../source/resource/qx/mobile/scss/common/_all.scss 5:9         @import
  stdin 1:9                                                      root stylesheet
    at /Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:40224:18
    at Function.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:115868:16)
    at render_closure1.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:99335:12)
    at _RootZone.runBinary$3$3 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:34824:18)
    at _FutureListener.handleError$1 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33354:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33661:49)
    at Object._Future__propagateToListeners (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:4151:77)
    at _Future._completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33507:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33155:12)
    at Object._asyncRethrow (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3954:17)
    at /Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:23852:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3979:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33174:12)
    at _awaitOnObject_closure0.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33168:25)
    at _RootZone.runBinary$3$3 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:34824:18)
    at _FutureListener.handleError$1 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33354:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33661:49)
    at Object._Future__propagateToListeners (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:4151:77)
    at _Future._completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33507:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33155:12)
    at Object._asyncRethrow (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3954:17)
    at /Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:17655:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3979:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33174:12)
    at _awaitOnObject_closure0.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33168:25)
    at _RootZone.runBinary$3$3 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:34824:18)
    at _FutureListener.handleError$1 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33354:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33661:49)
    at Object._Future__propagateToListeners (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:4151:77)
    at _Future._completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33507:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33155:12)
    at Object._asyncRethrow (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3954:17)
    at /Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:17691:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3979:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33174:12)
    at _awaitOnObject_closure0.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33168:25)
    at _RootZone.runBinary$3$3 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:34824:18)
    at _FutureListener.handleError$1 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33354:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33661:49)
    at Object._Future__propagateToListeners (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:4151:77)
    at _Future._completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33507:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33155:12)
    at Object._asyncRethrow (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3954:17)
    at /Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:79209:24
    at _wrapJsFunctionForAsync_closure.$protected (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:3979:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33174:12)
    at _awaitOnObject_closure0.call$2 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33168:25)
    at _RootZone.runBinary$3$3 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:34824:18)
    at _FutureListener.handleError$1 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33354:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/will/dev/qooxdoo/known-good/node_modules/sass/sass.dart.js:33661:49)
From previous event:
    at Function.__P_144_8 (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:20570:69)
    at Function.all (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:20146:27)
    at wrapper._loadConfigAndStartMaking (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:46442:26)
    at async wrapper.process (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:46397:9)
    at async wrapper.processCommand (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:35292:21)
    at async wrapper.main (/Users/will/dev/qooxdoo/known-good/node_modules/@qooxdoo/framework/lib/compiler/index.js:34766:11)
Compiling source version
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/Users/will/dev/qooxdoo/bootstrap/compiled/node/build/compiler'
Require stack:
- /Users/will/dev/qooxdoo/bootstrap/qx
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/will/dev/qooxdoo/bootstrap/qx:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/will/dev/qooxdoo/bootstrap/qx' ]
}

Node.js v20.5.0
  </code></pre>
</details>

It appears the intention is to use this mixin located at `source/resource/qx/scss/_mixin.scss`

```scss
@function rem($value, $factor: 1.0) {
```

However the naming choice conflicts with something else (possibly the builtin CSS function as mentioned by @p9malino26), and this mixin is not favored by the SASS compiler.

This issue is probably caused by not importing the mixin into all the locations it is used in.

The best solution is probably to give the function a more appropriate name which does not infringe on vanilla terms or conventions.

**Comment by hkollmann** [comment]
Same happens in windows!
